FROM node:18.19.1-alpine3.19

ARG UID
ARG GID
ARG NODE_ENV
ARG USER=${UID:-node}
ARG GROUP=${GID:-node}
ENV NODE_ENV=${NODE_ENV:-development}

WORKDIR /app

COPY . /app

WORKDIR /app/src
ENTRYPOINT ["/bin/sh", "-c" , "npm install && npm run start:debug"]
